# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_snn_rank <- function(neighbors) {
    .Call('_scran_build_snn_rank', PACKAGE = 'scran', neighbors)
}

build_snn_number <- function(neighbors) {
    .Call('_scran_build_snn_number', PACKAGE = 'scran', neighbors)
}

combine_rho <- function(Ngenes, first, second, Rho, Pval, Limited, Order) {
    .Call('_scran_combine_rho', PACKAGE = 'scran', Ngenes, first, second, Rho, Pval, Limited, Order)
}

combine_simes <- function(Pvals, logp) {
    .Call('_scran_combine_simes', PACKAGE = 'scran', Pvals, logp)
}

combine_holm_middle <- function(Pvals, logp, prop) {
    .Call('_scran_combine_holm_middle', PACKAGE = 'scran', Pvals, logp, prop)
}

compute_Top_statistic_from_ranks <- function(Ranks, prop) {
    .Call('_scran_compute_Top_statistic_from_ranks', PACKAGE = 'scran', Ranks, prop)
}

choose_middle_effect_size <- function(Pvals, Effects, prop) {
    .Call('_scran_choose_middle_effect_size', PACKAGE = 'scran', Pvals, Effects, prop)
}

compute_blocked_stats_lognorm <- function(mat, block, nblocks, sf, pseudo) {
    .Call('_scran_compute_blocked_stats_lognorm', PACKAGE = 'scran', mat, block, nblocks, sf, pseudo)
}

compute_blocked_stats_norm <- function(mat, block, nblocks, sf) {
    .Call('_scran_compute_blocked_stats_norm', PACKAGE = 'scran', mat, block, nblocks, sf)
}

compute_blocked_stats_none <- function(mat, block, nblocks) {
    .Call('_scran_compute_blocked_stats_none', PACKAGE = 'scran', mat, block, nblocks)
}

compute_residual_stats_lognorm <- function(qr, qraux, inmat, sf, pseudo) {
    .Call('_scran_compute_residual_stats_lognorm', PACKAGE = 'scran', qr, qraux, inmat, sf, pseudo)
}

compute_residual_stats_none <- function(qr, qraux, inmat) {
    .Call('_scran_compute_residual_stats_none', PACKAGE = 'scran', qr, qraux, inmat)
}

get_null_rho <- function(Ncells, Niters, Seeds, Streams) {
    .Call('_scran_get_null_rho', PACKAGE = 'scran', Ncells, Niters, Seeds, Streams)
}

get_null_rho_design <- function(qr, qraux, Niters, Seeds, Streams) {
    .Call('_scran_get_null_rho_design', PACKAGE = 'scran', qr, qraux, Niters, Seeds, Streams)
}

compute_rho_pairs <- function(gene1, gene2, ranks) {
    .Call('_scran_compute_rho_pairs', PACKAGE = 'scran', gene1, gene2, ranks)
}

cyclone_scores <- function(exprs, mycells, marker1, marker2, indices, niters, miniters, minpairs, seeds, streams) {
    .Call('_scran_cyclone_scores', PACKAGE = 'scran', exprs, mycells, marker1, marker2, indices, niters, miniters, minpairs, seeds, streams)
}

get_scaled_ranks <- function(exprs, subset, transpose, as_sparse) {
    .Call('_scran_get_scaled_ranks', PACKAGE = 'scran', exprs, subset, transpose, as_sparse)
}

overlap_exprs <- function(exprs, bygroup, lfc) {
    .Call('_scran_overlap_exprs', PACKAGE = 'scran', exprs, bygroup, lfc)
}

pool_size_factors <- function(exprs, pseudo_cell, order, pool_sizes) {
    .Call('_scran_pool_size_factors', PACKAGE = 'scran', exprs, pseudo_cell, order, pool_sizes)
}

subset_and_divide <- function(matrix, row_subset, col_subset, scaling) {
    .Call('_scran_subset_and_divide', PACKAGE = 'scran', matrix, row_subset, col_subset, scaling)
}

